<a href="https://colab.research.google.com/github/Billlee1231/ML/blob/master/tensorflow_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic TensorFlow concept

In [0]:
import tensorflow as tf
import numpy as np

**Tensors and Operations**

In [0]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [0]:
sess = tf.Session()
print (sess.run(total))

7.0


**TensorBoard**

In [0]:
# cannot see event file???
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())
writer.flush()

**dataset**

In [0]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [0]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-1.9116623  -0.47179765 -0.62457204]
[-1.2452114   1.2570441   0.04676733]
[ 1.6144222  -0.36838436 -2.262906  ]
[-0.63129663  0.7299787   1.4130275 ]
[-0.5769519  -0.24900801  1.6762766 ]
[ 0.74812263  0.27347195 -0.3603969 ]
[ 0.47334146 -1.0608655   0.2125263 ]
[-0.7156164  -0.22963569 -0.46340266]
[ 0.6604131   0.13935214 -0.37043443]
[ 0.7745225  -0.99507105 -0.32271618]


**Layers**

In [0]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[2.6343966]
 [3.5561745]]


**Feature Columns**

In [0]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.


In [0]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [0]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


**Training**

In [0]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(1000):
  _, loss_value = sess.run((train, loss))
  if i % 100==0:
    print(loss_value)

print(sess.run(y_pred))

0.58997655
0.07853598
0.04311534
0.023669798
0.012994421
0.0071337856
0.003916354
0.0021500345
0.0011803441
0.0006479944
[[-0.03045505]
 [-1.0147576 ]
 [-1.9990602 ]
 [-2.9833627 ]]
